AlchemicShop.WEB/Controllers/OrderController.cs
using AlchemicShop.BLL.DTO;
using AlchemicShop.BLL.Interfaces;
using AlchemicShop.WEB.Managers;
using AlchemicShop.WEB.Models;
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AlchemicShop.WEB.Controllers
{
    public class OrderController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly IOrderService _orderService;
        private readonly IOrderProductService _orderProductService;
        private readonly IShoppingCartService _scService;
        private readonly IProductService _productService;

        public OrderController(
            IMapper mapper,
            IUserService userService,
            IOrderService orderService,
            IOrderProductService orderProductService,
            IShoppingCartService scService,
            IProductService productService)
        {
            _mapper = mapper;
            _userService = userService;
            _orderService = orderService;
            _orderProductService = orderProductService;
            _scService = scService;
            _productService = productService;
        }

        [Authorize(Users = "Admin")]
        public async Task<ActionResult> GetOrderList()
        {
            ViewBag.Users = _mapper.Map<List<UserViewModel>>(
                await _userService.GetUsers()).ToList();

            return View(_mapper.Map<List<OrderViewModel>>(
                await _orderService.GetOrders()).ToList());
        }

        [Authorize(Users = "Admin")]
        public async Task<ActionResult> DeleteOrder(int? id)
        {
            var order = _mapper.Map<OrderViewModel>(
                await _orderService.GetOrder(id));

            await _orderService.DeleteOrder(
                    _mapper.Map<OrderDTO>(order));
            return RedirectToAction(nameof(GetOrderList));
        }

        [Authorize(Users = "Admin")]
        public async Task<ActionResult> EditOrder(int? id)
        {
            return View(_mapper.Map<OrderViewModel>(
                await _orderService.GetOrder(id)));
        }

        [HttpPost]
        [Authorize(Users = "Admin")]
        public async Task<ActionResult> EditOrder(OrderViewModel order)
        {
            if (ModelState.IsValid)
            {
                await _orderService.UpdateOrder(
                    _mapper.Map<OrderDTO>(order));
                return RedirectToAction(nameof(GetOrderList));
            }
            return View(order);
        }

        [Authorize(Users = "User")]
        public ActionResult CreateOrder()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Users = "User")]
        public async Task<ActionResult> CreateOrder(OrderViewModel orderViewModel)
        {
            if (ModelState.IsValid)
            {
                await _orderService.AddOrder(
                    _mapper.Map<OrderDTO>(
                        new OrderViewModel()
                        {
                            UserId = (int)Session["userLogin"],
                            Status = Models.Status.InTransit,
                            SheduledDate = orderViewModel.SheduledDate
                        }
                        ));

                var session = new SessionManager(HttpContext);
                var products = session.GetOrCreateProductList();

                foreach (var item in products)
                {
                    await _orderProductService.AddOrderProduct(
                       _mapper.Map<OrderProductDTO>(
                           new OrderProductViewModel
                           {
                               OrderId = await _scService.GetMaxOrderIdAsync(),
                               ProductId = item.Id,
                               Amount = item.Amount
                           }
                           ));
                    await _scService.UpdateProductAmount(item.Amount, item.Id);
                }
                session.RemoveAllProduct();
                return RedirectToAction("Index", "Home");
            }
            return View(orderViewModel);
        }

        public async Task<ActionResult> GetOrderDetails(int? id)
        {
            ViewBag.GetOrderSum = await _orderService.GetOrderSum(id);

            ViewBag.GetProductName = _mapper.Map<List<ProductViewModel>>(
                await _productService.GetProducts()).ToList();

            var orderDetails = _mapper.Map<List<OrderProductViewModel>>
                (await _orderProductService.GetOrderProductsId(id)).ToList();

            if(orderDetails.Count>0 && orderDetails != null)
            {
                return View(orderDetails);
            }

            return RedirectToAction(nameof(GetOrderList));
        }

        [Authorize(Users = "User")]
        public async Task<ActionResult> GetUserOrders()
        {
            ViewBag.GetUserName = _mapper.Map<List<UserViewModel>>(
                await _userService.GetUsers()).ToList();

            var userOrders = _mapper.Map<List<OrderViewModel>>
                (await _orderService.GetUserOrderList((int)Session["userLogin"])).ToList();
            
            if (userOrders.Count > 0 && userOrders != null)
            {
                return View(userOrders);
            }
            return RedirectToAction(nameof(EmptyOrderHistory));
        }

        [Authorize(Users = "User")]
        public ActionResult EmptyOrderHistory()
        {
            return View();
        }
    }
}

AlchemicShop.WEB/Controllers/ShoppingCartController.cs
using AlchemicShop.BLL.Interfaces;
using AlchemicShop.WEB.Managers;
using AlchemicShop.WEB.Models;
using AutoMapper;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AlchemicShop.WEB.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartController(
            IMapper mapper,
            ICategoryService categoryService,
            IProductService productService,
            IShoppingCartService shoppingCartService)
        {
            _mapper = mapper;
            _categoryService = categoryService;
            _productService = productService;
            _shoppingCartService = shoppingCartService;
        }

        public async Task<ActionResult> AddProduct(int? id)
        {
            if (id != null)
            {
                var session = new SessionManager(HttpContext);
                var curCartAmount = session.GetOrCreateProductList();
                var product = _mapper.Map<ProductViewModel>
                    (await _productService.GetProduct(id));
                product.Amount = 1;

                if (curCartAmount.Count == 0)
                {
                    session.AddProduct(product);
                }
                else
                {
                    foreach (var item in curCartAmount)
                    {
                        if (item.Id == product.Id)
                        {
                            if (await _shoppingCartService.IsEnoughProduct(product.Id, item.Amount))
                            {
                                session.AddProduct(product);
                                return RedirectToAction(nameof(GetCart));
                            }
                            else
                            {
                                return RedirectToAction("GetProductList", "Product");
                            }
                        }
                    }

                    foreach (var item in curCartAmount)
                    {
                        if (item.Id != product.Id)
                        {
                            session.AddProduct(product);
                            return RedirectToAction(nameof(GetCart));
                        }
                    }
                }
            }
            return RedirectToAction(nameof(GetCart));
        }

        public ActionResult DeleteCartItem(int? id)
        {
            if (id != null)
            {
                var session = new SessionManager(HttpContext);
                if (session != null)
                {
                    session.DeleteProduct(id);
                    return RedirectToAction(nameof(GetCart));
                }
            }
            return RedirectToAction(nameof(GetCart));
        }

        public ActionResult EditCartAmount(int? id)
        {
            if (id != null)
            {
                var session = new SessionManager(HttpContext);
                if (session != null)
                {
                    return View(session.GetIdProduct(id));
                }
            }
            return RedirectToAction(nameof(GetCart));
        }

        [HttpPost]
        public async Task<ActionResult> EditCartAmount(ProductViewModel product)
        {
            if (await _productService.IsEnoughProduct(product.Id, product.Amount))
            {
                ViewBag.AmountMsg = "";
                if (ModelState.IsValid)
                {
                    var session = new SessionManager(HttpContext);
                    session.EditProduct(product);
                    return RedirectToAction(nameof(GetCart));
                }
                return View(product);
            }
            ViewBag.AmountMsg = "Choose another amount";
            return View(product);
        }

        public ActionResult GetCart()
        {
            var session = new SessionManager(HttpContext);
            var products = session.GetOrCreateProductList();
            ViewBag.GetCartSum = session.GetCartSum(products);
            return View(products);
        }

        public ActionResult RemoveCart()
        {
            var session = new SessionManager(HttpContext);
            session.RemoveAllProduct();
            return RedirectToAction(nameof(GetCart));
        }
    }
}

AlchemicShop.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <ul class="nav">
                    <li class="nav-item">
                        <div class="layout-img">
                            <img src="~/Content/Images/Layout/layout_moon.gif">
                        </div>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">@Html.ActionLink("Home", "Index", "Home")</p>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">@Html.ActionLink("About", "About", "Home")</p>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">@Html.ActionLink("Product", "GetProductList", "Product")</p>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">@Html.ActionLink("Category", "GetCategoryList", "Category")</p>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">@Html.ActionLink("Cart", "GetCart", "ShoppingCart")</p>
                    </li>
                    @if (@HttpContext.Current.User.Identity.Name == "User")
                    {
                        <li class="nav-item">
                            <p class="nav-link">@Html.ActionLink("My orders", "GetUserOrders", "Order")</p>
                        </li>
                    }
                    @if (@HttpContext.Current.User.Identity.Name == "Admin")
                    {
                        <li class="nav-item">
                            <p class="nav-link">@Html.ActionLink("User", "GetUserList", "User")</p>
                        </li>
                        <li class="nav-item">
                            <p class="nav-link">@Html.ActionLink("Order", "GetOrderList", "Order")</p>
                        </li>
                    }
                    @if (@HttpContext.Current.User.Identity.Name != "Admin" &&
                         @HttpContext.Current.User.Identity.Name != "User")
                    {
                        <li> <p class="nav-link">@Html.ActionLink("Log in", "Login", "Account")</p></li>
                        <li> <p class="nav-link">@Html.ActionLink("Create account", "Register", "Account")</p></li>
                    }
                    else
                    {
                        <li><p class="nav-link">@Html.ActionLink("Log out", "Logoff", "Account")</p></li>
                    }
                </ul>
                @RenderBody()
                <hr />
            </div>
            <footer class="footer">
                <p>&copy; @DateTime.Now.Year - AstroDrave Project</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>